CREATE TABLE locations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  latitude VARCHAR(50),
  longitude VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE photos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255),
  path TEXT,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE screenshots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255),
  path TEXT,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255),
  path TEXT,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);